<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;ARM64;x64</Platforms>
      <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyName>Presentation.AlarmServer</AssemblyName>
    <AssemblyTitle>A cross-platform Alarm service for Powtechnology</AssemblyTitle>
    <MinVerTagPrefix>alarm-server/v</MinVerTagPrefix>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Infrastructure/Infrastructure.csproj" />
    <ProjectReference Include="..\Substituter\Application.Substituter.csproj" />
  </ItemGroup>
  <ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.6" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.6" />
	  <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6" />
	  <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="9.0.6" />
	  <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.6" />
	  <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.6" />
	  <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.6" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.6" />
	  <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.6" />
	  <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.6" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Microsoft.Data.SqlClient" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Enums\" />
  </ItemGroup>
</Project>