<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Antlr4 Include="TubeCube.g4">
      <Generator>MSBuild:Compile</Generator>
      <CustomToolNamespace>Powelectrics.Telemetry.FileProcessor</CustomToolNamespace>
      <Listener>True</Listener>
      <Visitor>True</Visitor>
      <Error>true</Error>
      <OutputType>CSharp</OutputType>
      <Package>Powelectrics.Telemetry.FileProcessor</Package>
    </Antlr4>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="Antlr4BuildTasks" Version="12.10.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.4" />
    <PackageReference Include="NLog" Version="5.3.4" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.1" />
  </ItemGroup>
</Project>
